### ISSUE TITLE
gnix_mr_key_t struct is too large

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1171]
Because the gnix_mr_key_t has an embedded struct, the contents of the struct are parsed and evaluated by the compiler for size before evaluating the outer structure. This results in a single structure 128 bits long, rather than 64 bits long because the embedded struct is assumed to be 64 bits in length and the other bytes of outside the embedded struct are assumed to be 64 bits in length as well. 

This is a bad assumption with respect to how the compiler would pack the entire structure. The result is that the key.value only returns the first qword, which contains the mdd and va, but not the flags or format. This means that flags are currently ignored by the provider,

**Comment by jswaro** [comment]
There is a fundamental problem with testing this. If a key was registered as read-only, the key would represent a read-write region, but the application doesn't know that. If an application tried to write to the region, libfabric wouldn't reject the request because it would see it as read-write permissions, even though the target mdd is read-only. It would fail at the GNI transaction, but that would be assumed as normal anyway, because the application would know it was read-only when it registered the memory. 

Happy coincidence: It is broken, but not in a way that people can tell.

**Comment by chuckfossen** [comment]
The reason the struct ends up being 128 bits is because the compiler will pad the inner struct to 64 bits since it is using uint64 types. You'd need to use the `packed` keyword if you want to get the rest of the fields packed up against the first bits.
So, the compiler is working as expected. No assumptions here.
BTW, bitfields are compiler specific.

How did this manifest itself? What do you mean by "This means that flags are currently ignored by the provider"? Do we assume the gnix_mr_key is 64 bits somewhere?
