### ISSUE TITLE
rdm_sr tests periodically fail with "Bad recv count"

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1311]
This seems to happen reasonably frequently when using --enable-debug for various tests.  I haven't looked for patterns, but maybe it's the same thing as #1095.

**Comment by sungeunchoi** [comment]
Got a bad counter value in the sep tests (again with --enable-debug)

```
[----] prov/gni/test/sep.c:571: Assertion failed: Bad send count i:0 send_cntr:28 sends:28
```

**Comment by hppritcha** [comment]
okay takes about 20 runs but I can reproduce the sep.c at 571 variant of this problem.

**Comment by hppritcha** [comment]
This does seem to be a timing thing where the thread progresses the state engine enough to get expected CQE's back but not enough to get counters updated.  probably need to be more careful about updating counters prior to CQs.  If I add some spin loops reading the cntr's before actually doing the test, the problem seems to go away, or at least be almost impossible to reproduce.

**Comment by hppritcha** [comment]
Okay I think the problem has to do with the ```fi_inject``` and equivalents.  If I remove tests making use of this function ( and equivalents) one does not observe the problem.
