### ISSUE TITLE
Finish implementing wait objects

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#150]
Some functionality like the wait object `wait` call was never implemented.

**Comment by hppritcha** [comment]
not sure who will get this issue at the moment.

**Comment by sungeunchoi** [comment]
Include new trywait interface.

**Comment by jshimek** [comment]
So I have pushed up an extremely rough batch of code for fi_wait implementation for the gni provider, it needs major cleansing and rework, and a good set of network type tests since fi_dgram_waitset is the only thing currently exercising it. But the unit tests I have written currently pass and all the existing unit tests continue to pass along with the cray_tests.
