### ISSUE TITLE
Collect requirements for OpenMPI

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#211]

**Comment by Pgrun** [comment]
Can we leverage the requirements gathered by the OFI WG and captured here?  http://downloads.openfabrics.org/WorkGroups/ofiwg/ofi_rqmts/

**Comment by hppritcha** [comment]
Hi Paul,

I think in this case we can just look at the source code that Intel put in
Open MPI.

Howard

2015-06-03 11:39 GMT-06:00 Paul Grun notifications@github.com:

**Comment by hppritcha** [comment]
OpenMPI currently uses libfabric in two places: in a Cisco specific BTL component, and in a MTL component developed by Intel.  The former is not of interest to us. 

The Intel MTL is pretty basic so is well suited for general proof of principal, but lacks features that will be
needed for scalability and good thread hot support.

The MTL requires a provider which provides the FI_EP_RDM  endpoint type.  It requires the FI_TAGGED provider capability as well.  The MTL also asks for FI_THREAD_ENDPOINT threading model, and FI_PROGRESS_AUTO for control progress.  It does not specify FI_PROGRESS_AUTO for data progress.

It uses the FI_AV_MAP map type, and the FI_CQ_FORMAT_TAGGED cq format flavor.  A single CQ is used both for FI_RECV and FI_SEND.

Tagged message specific usage of the MTL:
- uses 64 bits of tag, but does not check, nor request, a specific `mem_tag_format`.  This should probably be checked by the MTL - we will likely want to use info from the `mem_tag_format` to optimize how we hash receive requests in a tag match engine.
- uses `fi_tsend`
- uses `fi_trecv`
- uses `fi_trecvmsg` with a iov with `iov_count` = 1 and sometimes with `FI_PEEK` /`FI_CLAIM` to handle `MPI_Probe`, `MPI_Mprobe`, etc.
- uses `fi_cancel`, but doesn't support canceling of MPI sends - this will need to be fixed, but at the MTL level not within libfabric

The provider needs for `fi_tsend`, `fi_trecv`, etc. to always return without error - it doesn't check for
`-FI_EAGAIN`, for example.  

Implications for the GNI provider is that we will need to support tag-matching, no surprise.  We will also need to make sure that we continue to target making the provider thread safe, as the MTL is relying on that in the case that an app is initialized with `MPI_Init_thread` with `MPI_THREAD_MULTIPLE` requested.
The GNI provider's mem registration cache will be exercised quite a bit by this MTL.  The provider will also have to be able to accept potentially very large number of send/recv requests since the MTL isn't designed to handle `-FI_EAGAIN`.
