### ISSUE TITLE
Design for thread-hot support

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#221]
See #68 for background

**Comment by hppritcha** [comment]
We discussed how to use with scalable endpoints vs multiple FI_RDM_EP types for supporting thread-hot performance.  Since the design right now is to map different endpoints to different hw nics, this may be the simpler approach to support.  Realizing thread-host using scalable endpoints may be possible but will require some reworking of the provider.

**Comment by hppritcha** [comment]
Closing for now can reopen if necessary.
