### ISSUE TITLE
Discussion of tagged messaging support

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#227]

**Comment by jswaro** [comment]
So I'm looking at the tag matching code and I have the following questions:
- Do we have a provider global hint as so what the format looks like for the tag so that we can do smarter hashing/searching?
- Is there a tag format specific to the libfabric tag or is it dependent on the above layer?

If the tags are defined by the upper layer, in terms of format, then I don't see how we can get information from this. We wouldn't be aware of how they've formatted the tag to know what parts of the tag are important for searching/hashing other than the ignored bits. The discussion on source/msg_id yesterday doesn't seem to apply if we don't know the tag format that the upper layer uses.

**Comment by jswaro** [comment]
By provider global hint, I mean can the upper layer provide information to the provider during setup that might allow us to search tags more efficiently independent of the ignore bits used on a per-op basis?
