### ISSUE TITLE
Implement target-side counters

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#456]

**Comment by ztiffany** [comment]
This is related to the FI_REMOTE_CQ_DATA feature which is already mostly implemented for RMA.  This is achieved by sending the peer an SMSG message containing immediate data after the RMA is completed.

Additions needed to support counters are:
-For remote CQ events, check that peer capabilities include FI_RMA_EVENT before generating any events
  -The fix for issue #345 should include code to exchange peer endpoint capabilities
-After an RMA transfer is completed, check if the peer expects remote write or read counter events (this info also needs to be exchanged for each EP VC)
-If a peer wants remote counter events, send an SMSG message in the same way as is done for remote CQ  data events

This should wait for #345.
