### ISSUE TITLE
Implement scalable endpoints

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#710]
- fi_scalable_ep
- fi_scalable_ep_bind
- fi_tx_context
- fi_rx_context
- fi_rx_addr

**Comment by chuckfossen** [comment]
Will we support "named contexts"?
Will we support "context specific attributes"? "Support for per receive (or transmit) context attributes is provider specific and not guaranteed."

**Comment by hppritcha** [comment]
Excellent questions.  My take on the "named contexts" is that if we are supporting `fi_rx_addr` then we are supporting "named contexts" - the issuer of a message (`fi_send` or `fi_tsend`) can target a given RX context at the target EP by getting the addr from `fi_rx_addr output.`  I think we should support this.  The way I was seeing it is there would be bits in the `cdm_id` field in `struct gnix_address` that would define the address for a given RX context.

I think we could support "context specific attributes" without a big problem since we'd effectively be using an `gnix_fid_ep` for each tx/rx pair.  

Right now, I was thinking of using a `gnix_ep_fid` for each rx/tx pair (although it doesn't appear that the app has to ask for same number of rx and tx contexts when creating an SEP.   We might need to tweak the `gnix_fid_ep` structure a bit to support this though.

**Comment by sungeunchoi** [comment]
Are there any implications for supporting FI_THREAD_COMPLETION (or any of the other thread safety models) for scalable endpoints?

**Comment by chuckfossen** [comment]
Howard, your gnix_sep_control() function always returns -FI_ENOSYS. I think it should return success for FI_ENABLE. Does that sound right?

**Comment by hppritcha** [comment]
@chuckfossen - I think your correct, return `FI_SUCCESS`
