### ISSUE TITLE
rdm_fi_pdc tests periodically fail when run under valgrind

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#752]
One or more of the tests sometimes get the following assertion:

```
Assertion failed: The expression (s_state) == (S_STATE_DONE) is false
```

**Comment by e-harvey** [comment]
When running the `rdm_fi_pdc` tests with `FI_LOG_LEVEL=trace` the test `rdm_fi_pdc::peek_discard_unique_tags` fails intermittently.  When a failure occurs for `peek_discard_unique_tags` it is due to the assertion failure noted above.  Also, when the failure occurs the cpu hangs for ~2s in `__gnix_rndzv_req_send_fin()`; however, when `rdm_fi_pdc::peek_discard_unique_tags` passes the cpu spends < 1s in __gnix_rndzv_req_send_fin().

Running helgrind on the rdm_fi_pdc tests produced the following output: http://hastebin.com/umasadusig.md

@ztiffany

**Comment by jswaro** [comment]
It is possible that the rendzv message takes longer to finish than expected, and then another message finishes during that time and takes a tag that was meant for the first message. That would fail the ordering constraints of the test.

**Comment by e-harvey** [comment]
I believe so.  In that case, I think adding a lock around the first call to GNICqTestEvent in gnix_nic.c:__nic_rx_progress would solve that problem but may reduce performance.

**Comment by sungeunchoi** [comment]
This is not a problem.  It's user error (if the ordering matters).

@jswaro Since you are familiar with the test, can you look at #762?
