### ISSUE TITLE
GNIX Vector interfaces don't run through the ops structure

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#823]
@e-harvey 

The GNIX vector implementation was written to match the hashtable implementation, with locked and lockless options and and operations table to select between the two.  The ops table exists but is not used in the vector implementation.  Top level GNIX vector functions should do as the hastable implementation does and call internal functions through the ops pointer table.  Tests may also need to be updated to use the top level API.

**Comment by e-harvey** [comment]
The interfaces to the gnix_vector were left exposed in the header since they might provide better performance on the KNLs.  After investigating whether there is a performance hit on KNLs using the ops table we can decide whether to remove the interfaces from the header.

**Comment by e-harvey** [comment]
There has been some confusion about the gnix vector versus the gnix hashtable implementation.  The gnix hashtable uses the ops table internally, within the exposed API interfaces to select between locked and lockless operations.  The gnix vector was designed to use the ops table externally in place of the vector API -- the ops table calls the vector API, potentially wrapping the call to the API within a lock depending on how the vector was initialized.

In my mind, the decision for this issue should be to either remove the vector interfaces from the gnix header so that the user can only access the vector operations via the ops table or change the vector code to be like the hashtable by using the ops table internally.

@sungeunchoi @jswaro

**Comment by jswaro** [comment]
Definitely leave the vector interfaces in the header. Generally, you don't interact with a data structure's internal framework without good reason. 

I'd recommend changing the code to be like the hashtable. If you are concerned about the performance, we can look at your code and search for a simple solution, if one exists.
