### ISSUE TITLE
fi_getname should return error if EP isn't enabled

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#890]
Turns out that `fi_getname` should not return `FI_SUCCESS` if the supplied ep hasn't been enabled yet.  This behavior is described in the fi_cm man page.  The GNI provider should check
whether or the not the EP has been enabled, and probably return `-FI_EINVAL` if the EP has not yet been enabled.

**Comment by j-xiong** [comment]
The man page only says fi_getname is not guaranteed to return a valid address if the endpoint is not enabled or an address is set. However, a provider can return success if it is able to return valid address.

**Comment by hppritcha** [comment]
I think we need to discuss this at one of our bi-weekly telecons.  Users of libfabric are finding this behavior confusing.

**Comment by sungeunchoi** [comment]
I just had a bit of confusion myself here.  I called fi_getname with len=0 to get the size of addrlen, and the sockets provider returned -FI_EOPBADSTATE because the endpoint was not enabled.  So in this case, I wasn't even asking it to return an address, and it returned error.  This doesn't seem quite right.

**Comment by sungeunchoi** [comment]
We think that the behavior matches the man page.
